import torch
device=torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')


AGGR_MEAN = 'mean'
AGGR_GEO_MED = 'geom_median'
AGGR_FOOLSGOLD='foolsgold'
AGGR_PCA_DEFLECT = 'pca-deflect'
MAX_UPDATE_NORM = 1000  # reject all updates larger than this amount
patience_iter=20
AGGR_KRUM = 'krum'
AGGR_TRIMMED_MEAN = 'trimmed_mean'
AGGR_BULYAN = 'bulyan'
AGGR_CRFL='crfl'
AGGR_FEDAVGLR='fedavglr'
AGGR_MEDIAN='median'
AGGR_MKRUM = 'mkrum'
AGGR_FLTRUST='fltrust'
AGGR_FEDLDP='fedldp'
AGGR_FEDCDP='fedcdp'
AGGR_DNC = 'dnc'
AGGR_NAB = 'nab'
AGGR_NPD = 'npd'

TYPE_LOAN='loan'
TYPE_CIFAR='cifar'
TYPE_MNIST='mnist'
TYPE_FMNIST='fmnist'
TYPE_EMNIST='emnist'
TYPE_CIFAR100 = "cifar100"
TYPE_TINYIMAGENET='tiny-imagenet-200'

PCA_DEFLECT_TRUST_FACTOR = 0.01

PCA_DEFLECT_CONFIDENCE_THRESHOLD = 0.005

PCA_DEFLECT_DBSCAN_EPS_NORMAL = 1
PCA_DEFLECT_DBSCAN_EPS_FLAGGED = 100
PCA_DEFLECT_MIN_SAMPLES = 2

PCA_DEFLECT_RANDOM_TRIGGER_DETECTION_ON = True
PCA_DEFLECT_MIN_ROUNDS_FOR_TRIGGER_DETECTION = 3 #trigger detection epoch
PCA_DEFLECT_TRIGGER_DETECTION_ONCE = True

PCA_DEFLECT_TRACK_METRICS = True
PCA_DEFLECT_LOG_DETECTION_STATS = True

PCA_DEFLECT_FEATURE_LAYER = 'fc2'
PCA_DEFLECT_PCA_COMPONENTS = 2
PCA_DEFLECT_KMEANS_CLUSTERS = 2

PCA_DEFLECT_MAINTAIN_HISTORY = True
PCA_DEFLECT_HISTORY_BUFFER_SIZE = 5

PCA_DEFLECT_ENABLE_FILTERING = True
PCA_DEFLECT_FILTER_BATCH_SIZE = 16
PCA_DEFLECT_CONFIDENCE_FILTER_THRESHOLD = 0.3
PCA_DEFLECT_ENABLE_DUAL_TRAINING = True
PCA_DEFLECT_FC2_FEATURE_EXTRACTION = True

PCA_DEFLECT_MIN_ROUNDS_BEFORE_DETECTION = 20

NPD_EPOCHS = 100
NPD_LR = 0.01
NPD_WEIGHT_DECAY = 0.0001
NPD_CLEAN_RATIO = 0.05
NPD_TPGD_EPS = 0.3
NPD_TPGD_EPS_ITER = 0.1
NPD_TPGD_STEPS = 2
NPD_BOUNDS = (-3.0, 3.0)
NPD_WAIT_ROUNDS = 20
PCA_DEFLECT_OUTLIER_PERSISTENCE = 3

PCA_DEFLECT_IMMEDIATE_FLAGGING = True

AGGR_NAB = 'nab'
AGGR_NAB_PCA = 'nab_pca'

NAB_WAIT_ROUNDS = 20
NAB_LGA_EPOCHS = 50
NAB_CLEAN_MODEL_EPOCHS = 150

NAB_LGA_GAMMA = 0.5
NAB_ISOLATION_RATIOS = [0.01, 0.05, 0.10]
NAB_DEFAULT_ISOLATION_RATIO = 0.05

NAB_STAMP_SIZE = 10

NAB_LGA_LR = 0.1
NAB_LGA_MOMENTUM = 0.9
NAB_LGA_WEIGHT_DECAY = 1e-4

NAB_CLEAN_LR = 0.1
NAB_CLEAN_MOMENTUM = 0.9
NAB_CLEAN_WEIGHT_DECAY = 1e-4

NAB_LOSS_THRESHOLD_MULTIPLIER = 1.5
NAB_PERCENTILE_THRESHOLD = 5

NAB_MAX_SAMPLES_PER_CLIENT = 500
NAB_BATCH_SIZE_DETECTION = 32
NAB_BATCH_SIZE_CLEAN_TRAINING = 64

NAB_COMPATIBLE_DEFENSES = ['pca-deflect', 'foolsgold', 'mean']
NAB_RUN_BEFORE_AGGREGATION = True
NAB_RUN_AFTER_AGGREGATION = True

NPD_COMPATIBLE_ATTACKS = ['badnet', 'dba', 'edgecase']
NPD_POST_TRAINING_DEFENSE = True

NAB_MNIST_STAMP_VALUE = 0.0
NAB_CIFAR_STAMP_VALUE = 0.0
NAB_TINYIMAGENET_STAMP_VALUE = 0.0

NAB_PHASE_WAIT = "wait"
NAB_PHASE_DETECTION = "detection"
NAB_PHASE_TRAINING = "nab_training"

NAB_DEBUG_MODE = False
NAB_MIN_PARTICIPATING_CLIENTS = 3
NAB_MAX_PARTICIPATING_CLIENTS = 50

import os
NAB_LOG_DIR = './logs/nab/'
NAB_MODEL_SAVE_DIR = './saved_models/nab/'
NAB_RESULTS_DIR = './results/nab/'

PCA_DEFLECT_LOG_DIR = './logs/pca_deflect/'
PCA_DEFLECT_RESULTS_DIR = './results/pca_deflect/'

NPD_LOG_DIR = './logs/npd/'
NPD_MODEL_SAVE_DIR = './saved_models/npd/'
NPD_RESULTS_DIR = './results/npd/'

for directory in [NAB_LOG_DIR, NAB_MODEL_SAVE_DIR, NAB_RESULTS_DIR, 
                  PCA_DEFLECT_LOG_DIR, PCA_DEFLECT_RESULTS_DIR,
                  NPD_LOG_DIR, NPD_MODEL_SAVE_DIR, NPD_RESULTS_DIR]:
    os.makedirs(directory, exist_ok=True)

print(f"[CONFIG] Configuration loaded with PCA-Deflect Defense and NPD Defense support")
print(f"[CONFIG] Device: {device}")